[versions]
jdkRelease = "17"
minGradle = "9.0.0"
kotlin = "2.3.20-Beta2"
agp = "9.0.0"

[libraries]
androidx-gradlePluginLints = "androidx.lint:lint-gradle:1.0.0-alpha05"
# Dummy to get renovate updates, the version is used in rootProject build.gradle with spotless.
ktfmt = "com.facebook:ktfmt:0.61"

junit-bom = "org.junit:junit-bom:6.0.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
jetbrains-dokka = "org.jetbrains.dokka:2.1.0"
mavenPublish = "com.vanniktech.maven.publish:0.36.0"
pluginPublish = "com.gradle.plugin-publish:2.0.0"
spotless = "com.diffplug.spotless:8.2.1"
